apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: edu-inspiring-stonebraker
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - nodePort: <port>
      port: 80
      targetPort: 80
